# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a0e19bc176607bcc9178f4a501c6f09d0853e94553e1ca0b621c0b3ddee41ea5c86e694658c71f345c58c7559068c2ba75e5ca857c4d4acb1df18b331f425bd

test:
  secret_key_base: 4aa16538c4247d62fd34d2f1eb9b00ec9c3c0d319bb92038a0e1e3cad21ca395c4464110f3e1592e7c7eed308ec01c2624ae1b56f042b19bebbd305302cb2df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
